export const NAME_MAX_LENGTH = 16;
export const NAME_MIN_LENGTH = 1;
export const DESCRIPTION_MAX_LENGTH = 140;
export const IMAGES_URLS_MAX_NUMBER = 5;


export const CAT = "CAT";
export const DOG = "DOG";

export const TYPES = [
    CAT,
    DOG
];

export const MALE = 'M';
export const FEMALE = 'F';

export let BREEDS = {};
BREEDS[CAT] = [
    'Abyssinian',
    'Aegean'
];


export const EXCEPTION_MESSAGE_NAME_MAXIMUM_LENGTH = "MAXIMUM PET'S NAME LENGTH EXCEEDEd";
export const EXCEPTION_MESSAGE_NAME_MINIMUM_LENGTH = "BEYOND MINIMUM PET'S NAME LENGTH";
export const EXCEPTION_MESSAGE_TYPE = "PET'S TYPE DOESN'T EXIST";
export const EXCEPTION_MESSAGE_BREED = "PET'S BREED DOESN'T EXIST";
export const EXCEPTION_MESSAGE_GENDER = "PET'S GENDER DOESN'T EXIST";
export const EXCEPTION_MESSAGE_DESCRIPTION_MAX_LENGTH = "MAXIMUM PET'S DESCRIPTION LENGTH EXCEEDEd";
export const EXCEPTION_MESSAGE_IMAGES_URL_MAXIMUM_NUMBER = "MAXIMUM PET'S IMAGES EXCEEDEd";



