export const SALT_LENGTH = 16; // in bytes
export const HASH_NUMBER_OF_ITERATIONS = 1000;
export const HASH_LENGTH = 128; // in bytes
export const HASH_DIGEST = `hex`;

export const NAME_MAXIMUM_LENGTH = 16;
export const PASSWORD_MAXIMUM_LENGTH = 64;
export const PASSWORD_MINIMUM_LENGTH = 8;

export const LATITUDE_MAXIMUM_VALUE = 90;
export const LONGITUDE_MAXIMUM_VALUE = 180;
export const LATITUDE_MINIMUM_VALUE = -90;
export const LONGITUDE_MINIMUM_VALUE = -180;

export const FEMALE = 'F';
export const MALE = 'M';

export const EXCEPTION_MESSAGE_NAME_MAXIMUM_LENGTH = "EXCEEDED USER'S NAME MAXIMUM LENGTH";
export const EXCEPTION_MESSAGE_PASSWORD_MAXIMUM_LENGTH = "EXCEEDED USER'S PASSWORD MAXIMUM LENGTH";
export const EXCEPTION_MESSAGE_PASSWORD_MINIMUM_LENGTH = "USER'S PASSWORD LENGTH BEYOND THE ALLOWED LENGTH";
export const EXCEPTION_MESSAGE_GENDER_INVALID = "USER'S GENDER IS INVALID";
export const EXCEPTION_MESSAGE_EMAIL_INVALID = "USER'S EMAIL IS INVALID";
export const EXCEPTION_MESSAGE_EMAIL_DOES_NOT_EXISTS = "USER'S DOES NOT EXIST";
export const EXCEPTION_MESSAGE_EMAIL_ALREADY_EXISTS = "USER'S EMAIL ALREADY EXIST";
export const EXCEPTION_MESSAGE_LATITUDE_INVALID = "USER'S LOCATION IS INVALID (LATITUDE)";
export const EXCEPTION_MESSAGE_LONGITUDE_INVALID = "USER'S LOCATION IS INVALID (LONGITUDE)";

