name: Pet Club CI

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 5
            - name: Use node version ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Remove existing TypeScript
              run: |
                  npm uninstall typescript --no-save
                  npm uninstall tslint --no-save
            - name: install user dependencies
              run: |
                  npm install "microservices/user" --production=false
                  cd "microservices/user/" &&  npm install @typescript-eslint/eslint-plugin@4.12.0 --save-dev && npx eslint "./**.ts"
            - name: user and pets tests
              run: |
                npm install "microservices/user" --production=false
                cd "microservices/user/" && npm test
            - name: install chat dependencies
              run: |
                  npm install "microservices/chat" --production=false
                  cd "microservices/chat/" &&  npm install @typescript-eslint/eslint-plugin@4.12.0 --save-dev && npx eslint "./**.ts"
            - name: chat test
              run: |
                npm install "microservices/chat" --production=false
                cd "microservices/chat/" && npm test
